version: '3.8'

services:
  # PPB Facilities License Verification Service
  ppb-facilities-verification:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
      - CACHE_ENABLED=True
      - CACHE_BACKEND=redis
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - ppb-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis cache for facilities verification
  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ppb-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:

networks:
  ppb-network:
    driver: bridge

